# Generated by Django 4.2.1 on 2024-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
