# Generated by Django 4.2.1 on 2024-01-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session_id',
        ),
    ]
